channels:
  - conda-forge
dependencies:
  - tensorflow=1.4.0
  - numpy=1.18.5
  - cython=0.29.22
  - bitstring=3.1.7
  - configargparse=1.3
  - numba=0.52.0
  - dill=0.3.3
  - opencv=4.3.0
  - tqdm=4.58.0